using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using MouseKeyProxy.Common;

namespace MouseKeyProxy.Service.Device;

/// <summary>
/// FR-MKP-016 / TR-MKP-XFER-004: controls Samba share lifecycle and IP allowlist
/// (paired host + USB-connected PC only).
/// </summary>
public interface ISmbShareController
{
    /// <summary>Whether SMB management is enabled for this host.</summary>
    bool IsEnabled { get; }

    /// <summary>Share name advertised to clients.</summary>
    string ShareName { get; }

    /// <summary>Applies allowlist IPs to smb.conf hosts allow and reloads smbd when possible.</summary>
    /// <param name="allowedIps">IPs from <see cref="IShareAccessAllowlist"/>.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    Task ApplyAllowlistAsync(IReadOnlyList<string> allowedIps, CancellationToken cancellationToken = default);
}

/// <summary>
/// Linux Samba controller writing <c>/etc/samba/smb.conf.mkp</c> and optional include.
/// No-ops on non-Linux. Unit tests use a custom config path.
/// </summary>
public sealed class SmbShareController : ISmbShareController
{
    private readonly ILogger<SmbShareController> _logger;
    private readonly string _configPath;
    private readonly string _sharePath;
    private readonly string _shareName;

    /// <summary>Creates a controller.</summary>
    /// <param name="logger">Logger.</param>
    /// <param name="configPath">Path to write smb snippet (default /etc/samba/smb.conf.mkp).</param>
    /// <param name="sharePath">Filesystem path of the share root.</param>
    /// <param name="shareName">SMB share name.</param>
    public SmbShareController(
        ILogger<SmbShareController> logger,
        string? configPath = null,
        string? sharePath = null,
        string? shareName = null)
    {
        _logger = logger;
        _configPath = configPath
            ?? Environment.GetEnvironmentVariable("MKP_SMB_CONF")
            ?? "/etc/samba/smb.conf.mkp";
        _sharePath = sharePath
            ?? Environment.GetEnvironmentVariable("MKP_FOLDER_SHARE_ROOT")
            ?? "/mnt/mkp-deploy/share";
        _shareName = string.IsNullOrWhiteSpace(shareName)
            ? (Environment.GetEnvironmentVariable("MKP_SMB_SHARE_NAME") ?? "MouseKeyProxy")
            : shareName;
        IsEnabled = string.Equals(Environment.GetEnvironmentVariable("MKP_SMB"), "1", StringComparison.Ordinal)
            || OperatingSystem.IsLinux();
    }

    /// <inheritdoc />
    public bool IsEnabled { get; }

    /// <inheritdoc />
    public string ShareName => _shareName;

    /// <inheritdoc />
    public Task ApplyAllowlistAsync(IReadOnlyList<string> allowedIps, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var ips = (allowedIps ?? Array.Empty<string>())
            .Where(ip => !string.IsNullOrWhiteSpace(ip))
            .Select(ip => ip.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Always allow loopback for local diagnostics; never open to ALL.
        var hostsAllow = new List<string> { "127.0.0.1" };
        hostsAllow.AddRange(ips);
        var allowLine = string.Join(" ", hostsAllow);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by MouseKeyProxy SmbShareController — do not edit by hand");
        sb.AppendLine("[global]");
        sb.AppendLine("workgroup = WORKGROUP");
        sb.AppendLine("server string = MouseKeyProxy");
        sb.AppendLine("security = user");
        sb.AppendLine("map to guest = never");
        sb.AppendLine($"hosts allow = {allowLine}");
        sb.AppendLine("hosts deny = ALL");
        sb.AppendLine();
        sb.AppendLine($"[{_shareName}]");
        sb.AppendLine($"path = {_sharePath}");
        sb.AppendLine("browseable = yes");
        sb.AppendLine("read only = no");
        sb.AppendLine("guest ok = no");
        sb.AppendLine("valid users = mkp-share");

        var dir = Path.GetDirectoryName(_configPath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        File.WriteAllText(_configPath, sb.ToString());
        _logger.LogInformation(
            "SMB allowlist written to {Path}: hosts allow = {Hosts}",
            _configPath,
            allowLine);

        // Best-effort reload on Linux; ignore failures in unit tests / Windows.
        if (OperatingSystem.IsLinux() && IsEnabled)
        {
            try
            {
                // Prefer systemctl reload; fall back is no-op if samba not installed.
                using var proc = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = "systemctl",
                    Arguments = "reload smbd",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                });
                proc?.WaitForExit(5000);
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "smbd reload skipped");
            }
        }

        return Task.CompletedTask;
    }
}
